ui <- fluidPage(title = 'Shortened web Link Analysis Tool',
                theme = shinythemes::shinytheme('flatly'),
                
               mainPanel(width = 9,
                            tabsetPanel(
                              tabPanel(title = 'Exploratory Data Analysis',
                                       selectInput("plotcolumn",
                                                   label = "Select column for building the chart",
                                                   choices = c("referrer",
                                                               "VENDORNAME_OPERATINGSYSTEM",
                                                               "TYPE_HARDWAREPLATFORM", 
                                                               "DURATION_FROMCLICKTOCREATION",
                                                               "TIME_CLICKED")),
                                       #colnames(clicks)),
                                       selectInput("fillcolumn",
                                                   label = "Column fill option:",
                                                   choices = c("referrer",
                                                               "VENDORNAME_OPERATINGSYSTEM",
                                                               "TYPE_HARDWAREPLATFORM")),
                                       selectInput("chartstyle",
                                                   label = "Should the bar chart be stacked or side-by-side",
                                                   choices = c("stack",
                                                               "dodge")),
                                       sliderInput("filterlevel",
                                                   label = "Filter out low levels",
                                                   min = 0, max = 1000, step = 100, value = 100),
                                       plotOutput('barchart'),
                                       plotOutput('densityplot')),
                              
                              tabPanel(title = 'Data Frame',
                                       selectInput("select",
                                                   label = "Select Column to sort by",
                                                   choices = colnames(clicks)[1:35],
                                                   selected = 7),
                                       dataTableOutput('table'))
                              )))
