ui <- fluidPage(title = 'Shortened web Link Analysis Tool',
                theme = shinythemes::shinytheme('flatly'),
                
               mainPanel(width = 9,
                            tabsetPanel(
                              tabPanel(title = "Load Data",
                                       fileInput("file1", "Choose CSV file",
                                                 multiple = F,
                                                 accept = c("text/csv",
                                                            "text/comma-separated-values,text/plain",
                                                            ".csv")),
                                       tags$hr(),
                                       checkboxInput("header", "Header", T),
                                       radioButtons("sep","Separator",
                                                    choices = c(Comma = ",",
                                                                Semicolon = ";",
                                                                Tab = "\t"),
                                                    selected = ","),
                                       actionButton("do", "Pre-Process Data"),
                                       dataTableOutput('table')),
                              tabPanel(title = 'Exploratory Data Analysis',
                                       selectInput("plotcolumn",
                                                   label = "Select column for building the chart",
                                                   choices = c("referrer",
                                                               "VENDORNAME_OPERATINGSYSTEM",
                                                               "TYPE_HARDWAREPLATFORM", 
                                                               "DURATION_FROMCLICKTOCREATION",
                                                               "TIME_CLICKED")),
                                       #colnames(clicks)),
                                       selectInput("fillcolumn",
                                                   label = "Column fill option:",
                                                   choices = c("referrer",
                                                               "VENDORNAME_OPERATINGSYSTEM",
                                                               "TYPE_HARDWAREPLATFORM")),
                                       selectInput("chartstyle",
                                                   label = "Should the bar chart be stacked or side-by-side",
                                                   choices = c("stack",
                                                               "dodge")),
                                       sliderInput("filterlevel",
                                                   label = "Filter out low levels",
                                                   min = 0, max = 5000, step = 500, value = 500),
                                       plotOutput('barchart'),
                                       plotOutput('densityplot'))
                              
                              
                              )))
